### ISSUE TITLE
Send notification when device disconnected

### ISSUE THREAD

**Issue by mstruys** [IoTForDevices/AZ3166WeatherDevice#12]
Use change in device twin to figure out if a device disconnects. If so send email for hw reset.

**Comment by mstruys** [comment]
This can be realized by making use of Azure Event Grid and IoT Hub device disconnect event.

**Comment by dmitriyteteruk** [comment]
I would recommend to add Rule in IoT Central App that will count messages (telemetry) with time windowing. For example you device send telemetry every 5 minutes, It means that number of messages is 2 average in 10 minutes. So you can add rule that if Count is less then 2 during last 10 minutes - there is a connectivity problem.

**Comment by mstruys** [comment]
That is a good point. The firmware needs to be changed to support IoT Plug and Play, but at the time I will work on that, I will take your recommendation as well to fix this as you suggest in the IoT Central App. Thanks for the suggestion!
